# Terminology and notation {#terminology-notation}

I will introduce in this Section some notation that I will be using throughout this report.

I denote the random variable for an individual's survival time with \(S\); since it denotes time, \(S\) can assume any non-negative value. The lower-case \(s\) represent a specific value of interest drawn from \(S\) for a given individual. In the case of right censoring, I denote with \(C\) the random variable representing censoring time, and \(c\) its realisation. The observed time is denoted with \(T = \min(S, C)\), and its realisation is \(t\). Finally, I denote with \(D = I(S \le C)\) the random variable indicating either occurrence of the event of interest or censorship; analogously as before, its realisation is lower-case \(d\).

Next, I will define two of the main quantities of interest in survival analysis, the _survival function_ and the _hazard function_. They are both functions of the observed time \(t\) and are denoted by \(S(t)\) and \(h(t)\), respectively.

The survival function is the complement of the cumulative distribution function of the observed time \(T\) and represent the probability that a given individual survives^[I use the term _survives_ loosely speaking, for conciseness - formally, I refer to _not experiencing the event of interest_.] longer than a specified time \(t\):
\[
S(t) = 1 - F_T(t) = 1 - P(T \le t) = P(T > t)
\]
\(t\) ranges (theoretically) between 0 and infinity, hence the survival function can be plotted as a smooth, continuous function that tends to 0 as \(t\) goes to infinity. In practice, though, the survival function appears as a step function as (1) individuals can be observed at discrete times only and (2) not all individuals may experience the event before the end of the study.

The hazard function \(h(t)\) is the limit of the probability of the survival time \(T\) laying within an interval \([t, t + \Delta(t))\) given that an individual survived up to time \(t\) divided by the length of the interval \(\Delta(t)\), for \(\Delta(t)\) approaching zero:
\[
h(t) = \lim_{\Delta(t) \to 0} \frac{P(t \le T < t + \Delta(t) | T \ge t)}{\Delta(t)}
\]
It represent the instantaneous potential (e.g. risk) for the event to occur within the interval \([t, t + \Delta(t))\) (with \(\Delta(t) \to 0\)), given that the individual survived up to time \(t\). The hazard function is always non-negative, it can assume different shapes over time, and it has no upper bound.

The survival function and the hazard function are strictly related. In fact, there is a clearly defined mathematical relationship between them, and it is possible to derive the form of \(S(t)\) when knowing the form of \(h(t)\) (and vice versa). Formally:
\[
S(t) = \exp \left[ -\int_0^t h(u) \ du \right]
\]
\[
h(t) =  -\left[ \frac{d S(t) / dt}{S(t)} \right]
\]

Finally, a third quantity of interest in survival analysis that is strictly related to the survival and hazard functions is the cumulative hazard function \(H(t)\). The cumulative hazard function represents the accumulation of hazard (e.g. \(h(t)\)) over time, and can be defined as
\[
H(t) = \int_0^t h(u) \ du;
\]
it can conveniently be expressed in terms of survival function via the relationship \(H(t) = - \log S(t)\), or alternatively with \(S(t) = \exp(-H(t))\).
