# Simulating survival data {#simsurv}
 
In this Chapter I will present a flexible and efficient method to simulate survival data from a variety of parametric distributions, first introduced by @bender_2005. Then, I will present an extension that allows simulating from a variety of complex distributions proposed by @crowther_2013b.

Let \(h(t) = h_0(t) \exp(X \beta)\) be the hazard function of a proportional hazards model, with \(h_0(t)\) baseline hazard function and \(X\) a matrix of covariates with regression coefficients \(\beta\). Let \(H_0(t) = H_0(t) \exp(X \beta)\) be the corresponding cumulative hazard function, with \(H_0(t) = \int_0^t h_0(u) \ du\). The survival function \(S(t)\) and cumulative distribution function \(F(t)\) follow naturally: \(S(t) = \exp(-H(t))\) and \(F(t) = 1 - S(t) = 1 - \exp(X \beta)\). 

@bender_2005 showed that by letting
\[
F(\tau) = u, \ u \sim U(0, 1)
\]
and denoting the simulated survival time with \(\tau\), it is possible to derive \(\tau\) analytically by inverting \(H_0(t)\) if \(h_0(\tau) > 0\):
\[
\tau = H_0^{-1}(-\log(u) \exp(X \beta))
\]
The only requirement is for \(H_0(t)\) to be directly invertible, which happens to be the case when simulating from an exponential, Weibull, or Gompertz distribution for the baseline hazard \(h_0(t)\). The algorithm for simulating \(m\) survival times is as follows:

1. draw a vector \(u\) of \(m\) observations from a \(U(0, 1)\) distribution;

2. simulate \(X\) (e.g. a binary treatment from a Bernoulli distribution) and fix \(\beta\);

3. the survival times can be obtained directly by applying the formula \(H_0^{-1}(-\log(u) \exp(X \beta))\).

@bender_2005 derived the closed-form version of \(H_0^{-1}(t)\) for the exponential, Weibull, and Gompertz distributions, presented in Table \@ref(tab:closed-form-formulas-simsurv).

Table: (\#tab:closed-form-formulas-simsurv) Closed-form formulas for simulating survival data from an exponential, Weibull, or Gompertz distribution.

                                                    Exponential                                 Weibull                                                        Gompertz
--------------------------------------------------  ------------------------------------------  -------------------------------------------------------------  ---------------------------------------------------------------------------------
Hazard function \(h_0(t)\)                          \(\lambda\)                                 \(\lambda p t ^ {p - 1}\)                                      \(\exp(\gamma t)\)
Cumulative hazard function \(H_0(t)\)               \(\lambda t\)                               \(\lambda t ^ p\)                                              \((\lambda / \gamma) (\exp(\gamma t) - 1)\)
Inverse cumulative hazard function \(H_0^{-1}(t)\)  \(\lambda ^ {-1} t\)                        \((\lambda ^ {-1} t) ^ {1 / p}\)                               \((1 / \gamma) \log((\gamma / \lambda) t + 1)\)
Survival time \(\tau\)                              \(-\frac{\log(u)}{\lambda \exp(X \beta)}\)  \(\left[-\frac{\log(u)}{\lambda \exp(X \beta)}\right]^{1/p}\)  \((1 / \gamma) \log\left[1 - \frac{\gamma \log(u)}{\lambda\exp(X \beta)}\right]\)

The requirement requirement for \(H_0(t)\) to be directly invertible impedes the use of distributions other than the exponential, Weibull, or Gompertz - which could be appropriate in some setting but too restricting in others. @crowther_2013b generalised this method in order to accommodate more complex distributions, even with turning points, under a proportional hazards model. In brief, when the cumulative baseline hazard function is not invertible it is not possible to solve the equation \(F(\tau) = u\) for \(\tau\); assuming it is possible to write \(H_0(t)\) analytically - a broader assumption compared to assuming \(H_0(t)\) is invertible - it is possible to use root-finding methods to solve for \(\tau\) numerically (Section \@ref(compch-numroot)). Formally, the survival time \(\tau\) can be simulated as the root of the equation \(S(\tau) - u  = 0\).

@crowther_2013b present an example of their method by simulating from a two-components mixture distribution [@mclachlan_1994], defined by additive components on the survival scale:
\[
S_0(t) = \pi S_1(t) + (1 - \pi) S_2(t),
\]
with \(\pi \in [0, 1]\) mixing parameter. \(S_i(t)\) can be any standard parametric distribution. Choosing two Weibull components for the mixture distribution, it can be showed that a proportional hazards model has the form
\[
h(t) = \frac{\lambda_1 p_1 t ^ {p_1-1} \pi \exp(-\lambda_1 t ^ {p_1}) + \lambda_2 p_2 t ^ {p_2-1} (1 - \pi) \exp(-\lambda_2 t ^ {p_2})} {\pi \exp(-\lambda_1 t ^ {p_1}) + (1 - \pi) \exp(-\lambda_2 t ^ {p_2})} \exp(X \beta);
\]
the survival function can be obtained directly from \(h(t)\) in closed-form, plugged into the equation \(S(\tau) - u = 0\), and numerically solved for \(\tau\).
