# Informative visiting process {#infvp}

Healthcare consumption data is being used increasingly often in medical research, a succesful example being the CArdiovascular disease research using LInked Bespoke studies and Electronic health Records (CALIBER) programme [@denaxas_2012]. CALIBER was constructed by extracting and linking electronic health records from primary care, hospital care, and nationwide registries (including information such as social deprivation and living status), and it consists in more than 10 million adults with 400 million person-years of follow-up; this vast amount of data allows researchers to answer more relevant and detailed clinical questions, but poses new methodological challenges.

First and foremost, in observational, healthcare consumption data observation times are likely to be correlated with the underlying disease severity. For instance, individuals tend to have irregular observation times as patients with more severe conditions (or showing early symptoms of a disease) tend to visit their GP or go to the hospital more often than those with milder conditions (and no symptoms). Their worse disease status is also likely to be reflected in worse biomarkers being recorded as such visits, causing abnormal values of such biomarkers to be overrepresented and normal values to be underrepresented. Additionally, for diseases with a high mortality rate, a terminal event that truncates observation of the longitudinal process is likely to be informative in the sense that it likely correlates with disease severity. That is, dropout is likely to be informative as the tendency to dropout after the occurrence of a terminal event is related to the current level of the longitudinally recorded biomarker.

Traditional methods used to analyse longitudinal data rely on the assumption that the underlying mechanisms that controls the observation time is independent of disease severity; however, as I mentioned before, that is unlikely with healthcare consumption data. It can be showed that failing to account for informative dropout in a longitudinal study can yields biased estimates of the model parameters [@wu_1988]. Analogously, an explicit assumption when jointly modelling longitudinal and survival data (using the framework presented in Chapter \@ref(jm)) is that the timing and number of measurements for each subject should be non-informative, i.e. it does not associate with the survival part of the model. However, it is currently unknown whether violations of this assumption lead to invalid inference or not in the context of joint models.

The topic of informative observation times and informative censoring has been often object of many recent investigations. @liu_2008a developed a model that analyses repeated measures by taking into account informative observation times and an informative terminal event at the same time; they proposed a joint model formed by three submodels, a frailty model for the observation times, a mixed effects model for the longitudinal process, and a proportional hazards model for the terminal event. @ghosh_2011 proposed a joint longitudinal and survival model that handles multiple changepoints in the longitudinal profile by including random spline coefficients; the survival part of the models handles an informative terminal event by using a semiparametric Cox model. @han_2014 proposed a model for the joint distribution of the longitudinal process, the observation process, and the dropout process that uses, respectively, a semiparametric linear regression model for the longitudinal data and two accelerated failure time models for the observation and dropout process; their model is semiparametric in the sense that it leaves the distributional form and the dependence structure unspecified. @lesperance_2015 developed a joint model within the multi-state framework that handles examination times correlated with disease progression; they link transition intensities of a Markov model with a log-linear mixed model governing observation times through shared random effects. However, they do not integrate out the shared random effects from the model as their target of inference is the transition intensities conditional on the random effects. Analogously, there has been quite a lot of developments in the multi-state framework to handle informative visiting times and/or dropout. @sweeting_2010 developed a model (similar to a hidden Markov model) in the setting of a response variable irregularly and infrequently observed by conditioning on regularly collected auxiliary data. @lange_2015 generalise the work of @sweeting_2010 to better fit observational data settings rather than clinical trial data with informative missingness or observation times by modelling the disease process with a Markov model and the observation process with a Poisson process that depends on the underlying disease status. @lawless_2015 consider the effect of intermittent, irregular observation times on the estimation of Markov models; they show that it is not possible to estimate transition intensities in bi-directional Markov models with good precision when the gap between observation times is too big. They also show how the correlation between visit times and observed disease status can bias model assessment procedures, and propose an inverse intensity weighted estimation procedure for state prevalence. In brief, this approach consists in weighting each individual by their probability of being observed (or measured) at a given point in time; they discuss and develop this further in [@nazeri_rad_2017]. Finally, @li_2017 proposed a joint model for a longitudinal outcome and semicompeting risk data such as study dropout and death; they model the longitudinal process using a mixed model, and the semicompeting risks using two separate probit models.

In conclusion, joint models for longitudinal and survival data can handle effectively informative dropout in longitudinal study by modelling the longitudinal trajectory and the dropout process jointly. However, it is not clear whether presence of an informative visiting process affects inference from joint models. Further investigating this topic will form a good part of work planned for the second year of my PhD, as I will discuss in Chapter \@ref(future). This project will have important practical implications, as it aims to provide guidance to practitioners and applied researchers using joint models for longitudinal and survival data with their observational data.
