# Personal development {#pdevelop}

In this chapter I will introduce and briefly discuss the personal development activities I carried out during the first year of my PhD. In particular, I will present the supervisory meetings, training courses, and conferences I attended.

## Supervisory meetings

I have been having frequent meetings with my supervisors, formally and informally. Formal supervisory meetings, recorded on PROSE ([https://prose.le.ac.uk](https://prose.le.ac.uk)), have been held on average every other week, with summaries produced and shared between us. A comprehensive list is available on PROSE. Additionally, we held informal meetings to discuss developments and more urgent matters more often, whenever it was needed and every week on average.

## Training and courses

I have attended a wide variety of courses during my first year, both externally and internally to the University of Leicester. The external courses I attended are:

- _Efficient R Programming_, on November 8^th^ 2016, organised by the Royal Statistical Society in London. The instructor was Dr. Colin Gillespie, from the University of Newcastle, United Kingdom, and Jumping Rivers. The course covered how to program efficiently with R; in particular, it covered common pitfalls when writing R code, code profiling, RCpp, and parallel programming. General hints and tips were provided.

- _Introduction to causal inference_, on April 25^th^ and 26^th^ 2017, organised by the Biostatistics Research Group at the University of Leicester and delivered by Dr. Arvid Sjölander from Karolinska Institutet, Stockholm, Sweden. The course provided foundational concepts of causal inference such as the difference between association and causation, the counterfactual framework, exchangeability, directed acyclic graphs, methods for estimating a causal effect, etc. Additionally, it provided an introduction to more advanced methods such as intrumental variables and Mendelian randomisation.

- _Using simulation studies to evaluate statistical methods_, on May 22^nd^ 2017, organised by University College London. The course was delivered by Dr. Tim Morris, Prof. Ian White and Dr. Michael Crowther, and it covered the rationale for using simulation studies, important concepts to keep in mind when planning a simulation study, computational tools, estimates of uncertainty, and tools for improving reporting and dissemination.

- Workshop on _Joint modelling of longitudinal and time-to-event data with R_, on July 5^th^, 2017, organised by the Department of Biostatistics of the University of Liverpool. The course was delivered by Dr. Graeme Hickey, and provided an introduction to joint models of longitudinal and survival data, including extensions to incorporate competing risks and multiple longitudinal processes and a practical session using R. 

I have attended a few courses within the University and not offered on PROSE; specifically, I attended a course on _Time series analysis with R_ (November 10^th^, 2016), a course on _Data visualisation_ (November 15^th^, 2016), and a course on _High performance computing at Leicester_ (February 8^th^, 2017). The latter was particularly important, as it allowed me to make better use of the high-performance computing facilities offered by the University. I also attended the _Preparing to teach in higher education_ workshop, strand A (July 24^th^ and 27^th^ 2017).

Additionally, I have attended the following PROSE training sessions to develop personal and communication skills in research settings. These are listed below:

- _Planning your literature search_, October 21^st^ 2016;

- _Conducting your literature search_, October 25^th^ 2016 ;

- _Assertiveness_, November 14^th^ 2016;

- _Introduction to critical thinking_, December 15^th^ 2016;

- _Presentations A: Fundamentals of an effective presentation_, January 30^th^ 2017;

- _Communication in research and other work settings_, January 31^st^ 2017;

- _Enhancing your digital profile_, February 2^nd^ 2017;

- _Saying it with your abstract_, February 10^th^ 2017;

- _Designing a poster_, February 27^th^ 2017;

- _Leadership in research and other work environments_, February 28^th^ 2017;

- _Preparing for the probation review (Physical natural and medical sciences)_, May 30^th^ 2017.

## Conferences

I have attended a number of conferences during this year, in which I delivered the following oral presentations:

- Survival Analysis for Junior Researchers conference, held in Leicester, UK, on April 5^th^ and 6^th^ 2017. I delivered a talk titled _Direct likelihood maximisation using numerical quadrature to approximate intractable terms_;

- Statistical Analysis of Multi-Outcome Data (SAM) conference, held in Liverpool, UK, on July 3^rd^ and 4^th^ 2017. I delivered a talk titled _Impact of model misspecification in survival models with frailties_;

- Annual Conference of the International Society for Clinical Biostatistics conference, held in Vigo, Spain, on July 9^th^ to July 13^th^ 2017. I delivered two talks: a titled _Impact of model misspecification in survival models with frailties_ during the main conference, and a talk titled _Exploring results from simulation studies interactively_ during the Students' Day organised on July 13^th^.

Additionally, I delivered an oral presentation on previous work external to my PhD project during the 54^th^ ERA-EDTA Congress held in Madrid, Spain, between June 3^rd^ and June 6^th^. The ERA-EDTA Congress is the main conference in the field of Nephrology in Europe, with approximately 10,000 participants in 2017. I delivered my presentation, titled _Inappropriate prescription of nephrotoxic drugs to individuals with chronic kidney disease_, to an audience of clinicians, epidemiologists, clinical researchers, and other stakeholders.
